### ISSUE TITLE
visreg not working for models with RW spatiotemporal fields

### ISSUE THREAD

**Issue by ecophilina** [pbs-assess/sdmTMB#94] opened 2022-05-24 00:36 UTC
predict function call seems to crash on line 460 with the TMB::MakeADFun()

**Comment by seananderson** [comment] 2022-05-24 01:56
Fixed with [this](https://github.com/pbs-assess/sdmTMB/commit/e0ca58fa804f382d4b1a6120f083b1d309509437). This was caused by the more efficient unique-locations random effect prediction commits, but I have no idea why.

**Closed by seananderson** 2022-05-24 01:56 UTC
