### ISSUE TITLE
Trouble with inverse gamma 

### ISSUE THREAD

**Issue by seanhardison1** [pbs-assess/sdmTMB#35] opened 2020-11-29 00:56 UTC
I have some right skewed data that I'd like to model with an inverse gamma distribution, but the model doesn't seem to want to converge. Here's a simple example:

```
library(tidyverse)
library(sdmTMB)

pcod_spde <- make_mesh(pcod, c("X", "Y"), cutoff = 10)
plot(pcod_spde)

test <- pcod %>% 
  mutate(test_gamma = rgamma(nrow(.), shape = 1, scale = 1))

# works
sdmTMB(test_gamma ~ 1,
       family = Gamma(link = "log"),
       data = test,
       spde = pcod_spde, 
       spatial_only = TRUE)

# not working
sdmTMB(test_gamma ~ 1,
       family = Gamma(link = "inverse"),
       data = test,
       spde = pcod_spde, 
       spatial_only = TRUE)

```

Any ideas? Anyways, thanks for putting together such a cool and useful package!

**Comment by seananderson** [comment] 2020-11-29 07:07
Thanks for noting that! It should be fixed now.

The problem was that the default fixed-effect parameter initialization at 0 didn't make sense in this case. I've confirmed with simulated data that it seems to be estimating correctly, but the Gamma family with an inverse link does seem to have a higher chance of optimization problems compared to other families. I assume the spatial random fields can push the expected values in link space to negative values sometimes. Admittedly, I've rarely worked with the inverse link myself.

**Closed by seananderson** 2020-11-29 07:07 UTC

**Comment by seanhardison1** [comment] 2020-11-29 14:13
Thanks so much! That solved it.
